devpointlabs/HomeInventory2020

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, client/package.json, client/src/App.js, client/src/index.js, client/yarn.lock, config/initializers/devise_token_auth.rb, config/routes.rb, db/migrate/20200331213740_devise_token_auth_create_users.rb, db/migrate/20200331213947_add_trackable_to_users.rb, db/schema.rb
DC, I graciously request of you to merge installation files.
=> axios, router, antd, devise

client/package.json, client/src/components/FetchUser.js, client/src/components/ProtectedRoute.js, client/src/index.js, client/src/providers/AuthProvider.js, client/yarn.lock
Added user authentication components / provider, edited index.js, installed devise-axios.
=> Authentication Components

client/src/App.js, client/src/components/Album.js, client/src/components/Home.js, client/src/components/Inbox.js, client/src/components/Items.js, client/src/components/Login.js, client/src/components/Navbar.js, client/src/components/NoMatch.js, client/src/components/Policies.js, client/src/components/Register.js, client/src/components/UserPage.js
Created routes for navigation. Created a Navbar component with no actual navbar in it.
=> created routes for navigation

client/package.json, client/src/components/Navbar.js, client/yarn.lock
=> fixed navbar

app/controllers/application_controller.rb, client/src/App.js, client/src/components/Login.js, client/src/components/Register.js, client/src/index.js
=> Added Login and Register

client/src/components/Home.js, client/src/components/Navbar.js
created home page and nav bar for new users
=> home and home nav for new users

app/controllers/api/items_controller.rb, app/controllers/api/photos_controller.rb
Built out a basic photo controller. Will most likely have to change over the next couple days.
=> worked on photo controller

app/controllers/api/receipts_controller.rb
I created the receipts controller
=> created the receipts controller

app/controllers/api/documents_controller.rb
Hashed out documents_controller
=> Documents controller

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Login.js, client/src/components/Navbar.js, client/src/components/Register.js, client/src/components/Reports.js, client/src/providers/AuthProvider.js
working navbar with hardcoded sign out
=> navbar and home page

client/src/App.js, client/src/components/Items.js, client/src/components/Navbar.js, client/src/components/RenderItems.js
added axios get calls for locations and all the items that location has
=> working get calls for locations and items

client/package.json, client/src/components/forms/ItemForm.js, client/src/components/forms/LocationForm.js, client/yarn.lock
Just pushing up so we have all of our pieces in the same spot to get them working.
=> built out items/locations forms

client/src/components/Login.js, client/src/components/Register.js
new form pages for home inventory
=> changed the form page

client/src/components/Items.js
Made a mistake...fixed the mistake
=> resolved incorrect merge

client/src/components/Items.js, client/src/components/Receipts.js
=> woring code

client/src/components/Items.js
=> Active item style

client/src/components/ItemPhotos.js, client/src/components/Items.js, client/src/components/Receipts.js
=> show logic on tab components

client/src/components/Assessments.js, client/src/components/CustomTable.js, client/src/components/CustomTableM.js, client/src/components/House.js, client/src/components/Maintenances.js
styling for houses still need a form switch
=> house styling

client/src/components/House.js, db/seeds.rb
added seed and styling for home
=> added seed and styling for home

client/src/components/House.js, client/src/components/Policies.js, client/src/components/PolicyInfo.js
Still work in progress with Ryan
=> work in progress

app/controllers/api/photos_controller.rb, client/src/components/ItemFiles.js, client/src/components/ItemPhotos.js, client/src/components/Items.js, client/src/components/Policies.js, client/src/components/modals/UploadModal.js, client/src/components/uploaders/FileUploader.js, client/src/components/uploaders/PhotoUploader.js, db/seeds.rb
=> Items work continued

app/controllers/api/policies_controller.rb, app/models/home.rb, app/models/policy.rb, client/src/App.js, client/src/components/EditPolicy.js, client/src/components/House.js, client/src/components/ItemInfo.js, client/src/components/Policies.js, client/src/components/PolicyInfo.js, client/src/components/forms/PolicyForm.js, config/routes.rb, db/migrate/20200415233036_create_policies.rb, db/schema.rb, test/controllers/api/policies_controller_test.rb, test/fixtures/policies.yml, test/models/policy_test.rb
Very messy right now. Just pushing so others have the current policy info/copy
=> Policy page

client/src/components/Items.js, client/src/components/Policies.js
=> added styling

client/src/components/House.js
=> added styling to home

client/src/components/forms/ItemForm.js, client/src/components/forms/LocationForm.js, client/src/components/forms/ReceiptForm.js, client/src/components/modals/EditItemModal.js, client/src/components/modals/EditLocationModal.js
Now the forms are labeled the same across the board. Will have to do policy forms after that component gets completed.
=> minor congruency edits for forms

app/controllers/api/homes_controller.rb, app/controllers/api/receipts_controller.rb, client/src/components/modals/EditReceiptModal.js
=> Edit receipt photo
